# Generated by Django 3.2.18 on 2023-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
