# Generated by Django 3.2.18 on 2023-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0003_analysis_analysis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='analysis_status',
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='analysis_status',
            field=models.CharField(default='Created', max_length=20),
        ),
    ]
