# Generated by Django 3.2.18 on 2023-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0004_auto_20230411_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='access_group',
            field=models.CharField(default='New', max_length=30, null=True),
        ),
    ]
