# Generated by Django 3.2.18 on 2023-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0005_patient_access_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
