# Generated by Django 3.2.18 on 2023-04-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0005_auto_20230414_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfields',
            name='analysis_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
