# Generated by Django 3.2.18 on 2023-04-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0006_auto_20230410_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='files',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='files',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterUniqueTogether(
            name='userdisease',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdisease',
            name='disease_id',
        ),
        migrations.RemoveField(
            model_name='userdisease',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userdoctor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdoctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='userdoctor',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserDisease',
        ),
        migrations.DeleteModel(
            name='UserDoctor',
        ),
    ]
