# Generated by Django 3.2.18 on 2023-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0006_analysisfields_analysis_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfields',
            name='name',
        ),
        migrations.RemoveField(
            model_name='analysisfields',
            name='value',
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_10',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_11',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_12',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_13',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_14',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_15',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_16',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_17',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_18',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_19',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_20',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_21',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_22',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_23',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_24',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_25',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_26',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_27',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_28',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_29',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_30',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_6',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='field_9',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_10',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_11',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_12',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_13',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_14',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_15',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_16',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_17',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_18',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_19',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_20',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_21',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_22',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_23',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_24',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_25',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_26',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_27',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_28',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_29',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_3',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_30',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_4',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_5',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_6',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_7',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_8',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='analysisfields',
            name='value_9',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
