# Generated by Django 3.2.18 on 2023-04-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0008_auto_20230415_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfields',
            name='value_30',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
