# Generated by Django 3.2.18 on 2023-04-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0010_alter_analysisfields_value_30'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfields',
            name='id',
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='analysis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rda_frontend.analysis'),
        ),
    ]
