# Generated by Django 3.2.18 on 2023-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0011_auto_20230415_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfields',
            name='analysis_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
