# Generated by Django 3.2.18 on 2023-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0013_auto_20230418_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfields',
            name='value_1',
            field=models.CharField(default='Null', max_length=15, null=True, verbose_name='Показатель 1'),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_10',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_11',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_12',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_13',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_14',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_15',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_16',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_17',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_18',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_19',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_2',
            field=models.CharField(default='Null', max_length=15, null=True, verbose_name='Показатель 2'),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_20',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_21',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_22',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_23',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_24',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_25',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_26',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_27',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_28',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_29',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_3',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_30',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_4',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_5',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_6',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_7',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_8',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='analysisfields',
            name='value_9',
            field=models.CharField(default='Null', max_length=15, null=True),
        ),
    ]
