# Generated by Django 3.2.18 on 2023-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rda_frontend', '0014_auto_20230418_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='data_group',
            field=models.CharField(default='New', max_length=30, null=True),
        ),
    ]
